# Generated by Django 4.2.2 on 2023-07-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_de_tarjeta',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
